# Generated by Django 6.1.1 on 2026-09-11 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_password_token', models.CharField(blank=True, default='', max_length=60)),
                ('rest_password_expire_token', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='', max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('brand', models.CharField(default='', max_length=200)),
                ('category', models.CharField(choices=[('Computers', 'Computers'), ('Foods', 'Foods'), ('Kids', 'Kids'), ('Home', 'Home'), ('Animals', 'Animals'), ('Sports', 'Sports'), ('School', 'School'), ('Clothes', 'Clothes'), ('Vehicles', 'Vehicles'), ('Music', 'Music')], max_length=40)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('stock', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
