# Generated by Django 6.1.1 on 2026-09-13 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0003_alter_review_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(default='', max_length=400)),
                ('zipcode', models.CharField(default='', max_length=100)),
                ('street', models.CharField(default='', max_length=500)),
                ('state', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('phone_no', models.CharField(default='', max_length=20)),
                ('total_amount', models.IntegerField(default=0)),
                ('Payment_Status', models.CharField(choices=[('Paied', 'Paid'), ('Unpaied', 'Unpaied')], default='Unpaied', max_length=30)),
                ('payment_mod', models.CharField(choices=[('Cash on Delivered', 'Cash On Delivered'), ('CARD', 'Card')], default='CARD', max_length=30)),
                ('staus', models.CharField(choices=[('Proccesing', 'Proccesing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Proccesing', max_length=60)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('city', models.CharField(default='', max_length=400)),
                ('zipcode', models.CharField(default='', max_length=100)),
                ('street', models.CharField(default='', max_length=500)),
                ('state', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('phone_no', models.CharField(default='', max_length=20)),
                ('total_amount', models.IntegerField(default=0)),
                ('Payment_Status', models.CharField(choices=[('Paied', 'Paid'), ('Unpaied', 'Unpaied')], default='Unpaied', max_length=30)),
                ('payment_mod', models.CharField(choices=[('Cash on Delivered', 'Cash On Delivered'), ('CARD', 'Card')], default='CARD', max_length=30)),
                ('staus', models.CharField(choices=[('Proccesing', 'Proccesing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Proccesing', max_length=60)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='order.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
