# Generated by Django 6.1.1 on 2026-09-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='staus',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('Proccessing', 'Proccessing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Proccessing', max_length=60),
        ),
        migrations.AlterField(
            model_name='order',
            name='Payment_Status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='staus',
            field=models.CharField(choices=[('Proccessing', 'Proccessing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Proccessing', max_length=60),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='Payment_Status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
