# Generated by Django 6.1.1 on 2026-09-14 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_orderitem_staus_orderitem_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='Payment_Status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='country',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='payment_mod',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='state',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='street',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='zipcode',
        ),
    ]
