# Generated by Django 6.1.1 on 2026-09-14 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_orderitem_payment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='staus',
            new_name='status',
        ),
    ]
